#!/bin/sh                                                                                       

PID="org.webosinternals.saverestore"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/upstart/${PID} /etc/event.d/${PID}

# Install the dbus service
rm -f /usr/share/dbus-1/system-services/${PID}.service
cp $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/dbus/${PID}.service /usr/share/dbus-1/system-services/${PID}.service

# Install the saverestore scripts
mkdir -p /var/svc/org.webosinternals.saverestore
tar -C $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/scripts -c -f - . | \
tar -C /var/svc/org.webosinternals.saverestore -x -f -

# Start the service
/sbin/start ${PID}

exit 0
