#!/bin/sh

PID="org.webosinternals.saverestore"

# Stop the service
/sbin/stop ${PID}

# Remove the dbus service
rm -f /usr/share/dbus-1/system-services/${PID}.service /var/palm/system-services/${PID}.service

# Remove the upstart script
rm -f /etc/event.d/${PID} /var/palm/event.d/${PID}

exit 0
